# Generated by Django 4.2.19 on 2025-04-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='details',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
