# Generated by Django 4.2.19 on 2025-04-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_products_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
