# Generated by Django 4.2.19 on 2025-04-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_products_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='details',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='uncategorized', max_length=255),
        ),
    ]
