# Generated by Django 4.2.19 on 2025-04-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_products_details_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='details',
            field=models.CharField(default='uncategorized', max_length=255),
        ),
    ]
